version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres 
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: